# Limpa execuções antigas do workflow
name: Clean workflow runs

on:
  workflow_call:
    inputs:
      keep_last:
        description: 'Número de execuções a manter por workflow'
        required: false
        default: 10
        type: number

jobs:
  clean-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Excluir execuções antigas de cada workflow (incluindo órfãos)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          # Busca todas as execuções de workflow do repositório
          echo "Buscando todas as execuções de workflow do repositório"
          all_runs=$(gh api -H "Accept: application/vnd.github+json" \
            "/repos/$REPO/actions/runs?per_page=100" --paginate)

          # Agrupa execuções por nome de workflow
          echo "$all_runs" | jq -r '.workflow_runs[] | "\(.name)\t\(.id)\t\(.created_at)"' | sort | while IFS=$'\t' read -r workflow_name run_id created_at; do
            echo -e "$workflow_name\t$run_id\t$created_at"
          done > runs_by_workflow.txt

          # Para cada nome de workflow distinto, processa as execuções
          cut -f1 runs_by_workflow.txt | sort | uniq | while read -r workflow_name; do
            echo "\n»» Processando workflow: $workflow_name"
            # Lista execuções deste workflow, ordenadas do mais antigo para o mais novo
            grep -F "$workflow_name" runs_by_workflow.txt | sort -k3 | awk -F'\t' '{print $2}' > run_ids.txt
            total=$(wc -l < run_ids.txt)
            echo "Execuções encontradas: $total"
            cat run_ids.txt
            keep_last=${{ inputs.keep_last }}
            to_delete=$((total - keep_last))
            if [ $to_delete -gt 0 ]; then
              head -n $to_delete run_ids.txt | while read -r run_id; do
                run_id="$(echo "$run_id" | xargs)"
                gh api -X DELETE -H "Accept: application/vnd.github+json" "/repos/$REPO/actions/runs/$run_id"
                echo "Excluída execução $run_id do workflow $workflow_name"
              done
            else
              echo "Nenhuma execução para excluir no workflow $workflow_name"
            fi
          done
          rm -f runs_by_workflow.txt run_ids.txt
