# Limpa execuções antigas do workflow
name: Clean workflow runs

on:
  workflow_call: # Define como reutilizável
    inputs:
      keep_last:
        description: 'Número de execuções a manter por workflow'
        required: false
        default: 10
        type: number

jobs:
  clean-workflow-runs:
    runs-on: ubuntu-latest
    steps:

      - name: Excluir execuções antigas de cada workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          workflow_details=$(gh api -H "Accept: application/vnd.github+json" \
            "/repos/$REPO/actions/workflows" --jq '.workflows[] | "\(.id)\t\(.name)"')

          echo "$workflow_details" | while IFS=$'\t' read -r workflow_id workflow_name; do
            if [ -z "$workflow_id" ]; then # Handle potential empty lines if workflow_details is empty
              continue
            fi
            echo " "
            echo "Processando workflow ID: $workflow_id (Nome: $workflow_name)"
            # Paginação para buscar todas as execuções
            runs=""
            page=1
            while : ; do
              page_runs=$(gh api -H "Accept: application/vnd.github+json" \
                "/repos/$REPO/actions/workflows/$workflow_id/runs?per_page=100&page=$page" \
                --jq '.workflow_runs | sort_by(.created_at) | .[].id')
              if [ -z "$page_runs" ]; then
                break
              fi
              if [ -z "$runs" ]; then
                runs="$page_runs"
              else
                runs="$runs\n$page_runs"
              fi
              page=$((page + 1))
            done
            runs=$(echo "$runs" | grep -v '^$')
            echo "Execuções ordenadas (antigo -> novo):"
            echo "$runs"
            total=$(echo "$runs" | wc -l)
            keep_last=${{ inputs.keep_last }}
            to_delete=$(($total - $keep_last))
            if [ $to_delete -gt 0 ]; then
              old_runs=$(echo "$runs" | head -n $to_delete)
              for run_id in $old_runs; do
                gh api -X DELETE -H "Accept: application/vnd.github+json" \
                  "/repos/$REPO/actions/runs/$run_id"
                echo "Excluída execução $run_id do workflow $workflow_id (Nome: $workflow_name)"
              done
            else
              echo "Nenhuma execução para excluir no workflow $workflow_id (Nome: $workflow_name)"
            fi
          done