# Limpa execuções antigas do workflow
name: Clean workflow runs

on:
  workflow_call: # Define como reutilizável
    inputs:
      keep_last:
        description: 'Número de execuções a manter por workflow'
        required: false
        default: 10
        type: number

jobs:
  clean-workflow-runs:
    runs-on: ubuntu-latest
    steps:

      - name: Excluir execuções antigas de cada workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          workflow_details=$(gh api -H "Accept: application/vnd.github+json" \
            "/repos/$REPO/actions/workflows" --jq '.workflows[] | "\(.id)\t\(.name)"')

          echo "$workflow_details" | while IFS=$'\t' read -r workflow_id workflow_name; do
            if [ -z "$workflow_id" ]; then # Handle potential empty lines if workflow_details is empty
              continue
            fi
            echo " "
            echo "Processando workflow ID: $workflow_id (Nome: $workflow_name)"
            # Paginação para buscar todas as execuções
            run_ids=()
            page=1
            while : ; do
              page_runs=$(gh api -H "Accept: application/vnd.github+json" \
                "/repos/$REPO/actions/workflows/$workflow_id/runs?per_page=100&page=$page" \
                --jq '.workflow_runs | sort_by(.created_at) | .[].id')
              if [ -z "$page_runs" ]; then
                break
              fi
              while IFS= read -r id; do
                if [ -n "$id" ]; then
                  run_ids+=("$id")
                fi
              done <<< "$page_runs"
              page=$((page + 1))
            done
            echo "Execuções ordenadas (antigo -> novo):"
            for id in "${run_ids[@]}"; do
              echo "$id"
            done
            total=${#run_ids[@]}
            keep_last=${{ inputs.keep_last }}
            to_delete=$((total - keep_last))
            if [ $to_delete -gt 0 ]; then
              for ((i=0; i<to_delete; i++)); do
                run_id="${run_ids[$i]}"
                gh api -X DELETE -H "Accept: application/vnd.github+json" \
                  "/repos/$REPO/actions/runs/$run_id"
                echo "Excluída execução $run_id do workflow $workflow_id (Nome: $workflow_name)"
              done
            else
              echo "Nenhuma execução para excluir no workflow $workflow_id (Nome: $workflow_name)"
            fi
          done