name: Notify Crucible

on:
  workflow_call:
    inputs:
      repo_key:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CRUCIBLE_HOST: https://code.ncrcolibri.com.br
      RULE_PORT: 443

    steps:
      - name: Get public IP
        if: ${{ !contains(github.ref , 'dependabot') }}
        id: ip
        run: |
          PUBLIC_IP=$(curl -sS https://api.ipify.org) || true
          if [[ -z "$PUBLIC_IP" ]]; then
            echo "Service 1 failed. Trying Service 2..."
            PUBLIC_IP=$(curl -sS ifconfig.co/ip)
          fi
          echo "IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Update security group ingress
        if: ${{ !contains(github.ref , 'dependabot') }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          securityGroupIds=${{ secrets.SECURITY_GROUP_ID }}
          ruleDescription=GitHubActions-port-${{ env.RULE_PORT }}
          rulePort=${{ env.RULE_PORT }}
          publicIP=${{ env.IP }}
          
          securityGroupRuleId=$(aws ec2 describe-security-group-rules \
            --filter Name="group-id",Values="'$securityGroupIds'" | \
            jq -r '.SecurityGroupRules[0] | select(.CidrIpv4 == "'$publicIP/32'") | .SecurityGroupRuleId')
          
          if [ -z "${securityGroupRuleId}" ]; then
              aws ec2 authorize-security-group-ingress \
                --group-id $securityGroupIds \
                --ip-permissions '[{
                  "IpProtocol": "tcp", 
                  "FromPort": '$rulePort', 
                  "ToPort": '$rulePort', 
                  "IpRanges": [{
                    "CidrIp": "'$publicIP/32'", 
                    "Description": "'$ruleDescription'"
                  }]
                }]'
          fi

      - name: Update crucible repo index
        if: ${{ !contains(github.ref , 'dependabot') }}
        run: |
          curl --location \
               --request PUT \
               --header 'x-api-key: ${{ secrets.CRUCIBLE_API_KEY }}' \
               '${{ env.CRUCIBLE_HOST }}/rest-service-fecru/admin/repositories/${{ inputs.repo_key }}/incremental-index'
          
     
