name: 'Obter versão do INI'
description: 'Lê um arquivo INI e monta a versão com o número do workflow'

on:
  workflow_call:
    inputs:
      ini-path:
        required: true
        type: string
    outputs:
      valor:
        description: 'Versão formatada (Major.Minor.Release.Build)'
        value: ${{ jobs.obter-versao.outputs.valor }}

jobs:
  obter-versao:
    runs-on: windows-latest
    outputs:
      valor: ${{ steps.versao.outputs.valor }}
    steps:
      - id: versao
        shell: pwsh
        run: |
          $ini = Get-Content "${{ inputs.ini-path }}" | Where-Object { $_ -match '=' }
          $dict = @{}
          foreach ($line in $ini) {
            $parts = $line -split '='
            $key = $parts[0].Trim()
            $value = $parts[1].Trim()
            $dict[$key] = $value
          }
          $major = $dict['MajorVersion']
          $minor = $dict['MinorVersion']
          $release = $dict['Release']
          $build = $env:GITHUB_RUN_NUMBER
          $versao = \"$major.$minor.$release.$build\"
          echo \"valor=$versao\" >> $env:GITHUB_OUTPUT
