name: 'Obter versão do INI'
description: 'Lê um arquivo INI e monta a versão com o número do workflow'
inputs:
  ini-path:
    description: 'Caminho para o versao.ini'
    required: true
    default: agent/_build/versao.ini
outputs:
  valor:
    description: 'Versão formatada'
runs:
  using: "composite"
  steps:
    - shell: pwsh
      id: versao
      run: |
        $ini = Get-Content ${{ inputs.ini-path }} | Where-Object { $_ -match '=' }
        $dict = @{}
        foreach ($line in $ini) {
          $parts = $line -split '='
          $key = $parts[0].Trim()
          $value = $parts[1].Trim()
          $dict[$key] = $value
        }
        $major = $dict['MajorVersion']
        $minor = $dict['MinorVersion']
        $release = $dict['Release']
        $build = $env:GITHUB_RUN_NUMBER
        $versao = \"$major.$minor.$release.$build\"
        echo \"valor=$versao\" >> $env:GITHUB_OUTPUT